name: "museum"
version: "1.0.13"
usage: "test usage"
description: "test description"
useTunnel: true
command: "$HELM_PLUGIN_DIR/museum.sh"
hooks:
  install: "$HELM_PLUGIN_DIR/hooks.sh install"
  update: "$HELM_PLUGIN_DIR/hooks.sh update"
